name: Build, Push, and Deploy Docker on EC2

on: 
    push:
      branches:
        - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

      - name: check out repo
        uses: actions/checkout@v3

      - name: login to docker
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
            context: jupiter-website/
            push: true
            tags: ambefrankline/github:latest

      - name: deploy docker image to ec2
        uses: appleboy/ssh-action@master
        with:
            host: 3.94.109.167
            username: ec2-user
            key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
            script: |
               docker stop ambe || true
               docker rm ambe || ture
               docker pull ambefrankline/github:latest
               docker run -d --name ambe -p 80:80 ambefrankline/github:latest